# Generated by Django 4.2.20 on 2025-04-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=20, unique=True)),
                ('type_name', models.CharField(max_length=100)),
                ('has_period', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'income_types',
            },
        ),
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_code', models.CharField(max_length=20, unique=True)),
                ('period_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tax_periods',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(max_length=20)),
                ('period_type', models.CharField(max_length=10)),
                ('bracket_order', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bracket_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('relief_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tax_rates',
                'managed': True,
            },
        ),
    ]
