# Generated by Django 4.2.20 on 2025-04-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='tax_documents/')),
                ('content', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
