# Generated by Django 4.2.20 on 2025-04-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculator', '0002_taxdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='taxdocument',
            name='title',
        ),
        migrations.AlterField(
            model_name='taxdocument',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
