# Generated by Django 4.2.20 on 2025-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculator', '0003_alter_taxdocument_options_remove_taxdocument_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxdocument',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterModelTable(
            name='taxdocument',
            table='tax_calculator_taxdocument',
        ),
    ]
