# Generated by Django 4.2.20 on 2025-06-06 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_customuser_login_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthNewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_new_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'New User',
                'verbose_name_plural': 'New Users',
                'db_table': 'auth_new_user',
            },
        ),
    ]
