# Generated by Django 4.2.20 on 2025-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contactuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Tax Review',
                'verbose_name_plural': 'Tax Reviews',
                'db_table': 'tax_reviews',
                'ordering': ['-date'],
            },
        ),
    ]
