# Generated by Django 4.2.20 on 2025-05-20 05:26

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxFormDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='tax_form_docs/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tax_report_documents',
                'indexes': [models.Index(fields=['session_id'], name='tax_report__session_ed41c0_idx'), models.Index(fields=['last_accessed'], name='tax_report__last_ac_f88c90_idx')],
            },
        ),
    ]
