# Generated by Django 4.2.20 on 2025-05-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0002_taxformdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxformdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveIndex(
            model_name='taxformdocument',
            name='tax_report__session_ed41c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxformdocument',
            name='tax_report__last_ac_f88c90_idx',
        ),
        migrations.RemoveField(
            model_name='taxformdocument',
            name='last_accessed',
        ),
        migrations.AddField(
            model_name='taxformdocument',
            name='form_progress',
            field=models.CharField(default='uploaded', max_length=50),
        ),
        migrations.AddField(
            model_name='taxformdocument',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxformdocument',
            name='session_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxformdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
