# Generated by Django 4.2.20 on 2025-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0003_alter_taxformdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedTaxData',
            fields=[
                ('document_id', models.UUIDField(primary_key=True, serialize=False)),
                ('employment_data', models.JSONField(default=dict)),
                ('business_data', models.JSONField(default=dict)),
                ('investment_data', models.JSONField(default=dict)),
                ('other_income_data', models.JSONField(default=dict)),
                ('terminal_benefits_data', models.JSONField(default=dict)),
                ('qualifying_payments_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'extracted_tax_data',
            },
        ),
    ]
