# Generated by Django 4.2.20 on 2025-05-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0004_extractedtaxdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractedTaxData',
        ),
    ]
