# Generated by Django 4.2.20 on 2025-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0006_documentanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentanalysis',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Document analyses'},
        ),
        migrations.RemoveField(
            model_name='documentanalysis',
            name='session_id',
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='filename',
            field=models.CharField(default='unnamed_document.pdf', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='document_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='total_assessable_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
