# Generated by Django 4.2.20 on 2025-05-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0007_alter_documentanalysis_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentAnalysis',
        ),
    ]
