# Generated by Django 4.2.20 on 2025-05-29 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0008_delete_documentanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_results', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(max_length=50)),
                ('original_text', models.TextField()),
                ('extracted_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='tax_report.taxformdocument')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('field_path', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='tax_report.extractedcontext')),
            ],
        ),
    ]
