# Generated by Django 4.2.20 on 2025-05-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0009_document_extractedcontext_formfieldmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
