# Generated by Django 4.2.20 on 2025-06-12 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_report', '0010_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReportDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=10)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_year', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_report_downloads',
                'ordering': ['-download_date'],
            },
        ),
    ]
