# Generated by Django 4.2.20 on 2025-06-12 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_report', '0011_taxreportdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('Word', 'Word'), ('Excel', 'Excel')], max_length=10)),
                ('file_content', models.FileField(upload_to='downloaded_reports/')),
                ('download_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TaxReportDownload',
        ),
    ]
