# Generated by Django 4.2.20 on 2025-06-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0012_downloadedreport_delete_taxreportdownload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadedReport',
        ),
    ]
