# Generated by Django 4.2.20 on 2025-06-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_report', '0013_delete_downloadedreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedRedpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='downloaded_docs/')),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downloaded_redpots',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
