# Generated by Django 4.2.20 on 2025-06-12 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_report', '0014_downloadedredpot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DownloadedRedpot',
            new_name='DownloadedReports',
        ),
    ]
