# Generated by Django 4.2.20 on 2025-06-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0015_rename_downloadedredpot_downloadedreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='document',
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='document_name',
            field=models.CharField(default='tax_report.pdf', max_length=255),
        ),
        migrations.AlterModelTable(
            name='downloadedreports',
            table='downloaded_reports',
        ),
    ]
