# Generated by Django 4.2.20 on 2025-06-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0016_remove_downloadedreports_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedreports',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='downloaded_docs/'),
        ),
        migrations.AlterField(
            model_name='downloadedreports',
            name='document_name',
            field=models.CharField(max_length=255),
        ),
    ]
