# Generated by Django 4.2.20 on 2025-06-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0017_downloadedreports_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='document_name',
        ),
        migrations.AlterField(
            model_name='downloadedreports',
            name='document',
            field=models.FileField(upload_to='downloaded_docs/'),
        ),
        migrations.AlterModelTable(
            name='downloadedreports',
            table='downloaded_redpots',
        ),
    ]
