# Generated by Django 4.2.20 on 2025-06-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0018_remove_downloadedreports_document_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='downloadedreports',
            table='downloaded_reports',
        ),
    ]
