# Generated by Django 4.2.20 on 2025-06-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0020_saveddocument'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='downloadedreports',
            table='downloaded_redpots',
        ),
        migrations.DeleteModel(
            name='SavedDocument',
        ),
    ]
