# Generated by Django 4.2.20 on 2025-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0022_alter_downloadedreports_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedreports',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
