# Generated by Django 4.2.20 on 2025-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0023_downloadedreports_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedreports',
            name='assessable_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='balance_tax_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='document_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='tax_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='taxable_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='total_tax_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='downloadedreports',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='downloaded_docs/'),
        ),
    ]
