# Generated by Django 4.2.20 on 2025-06-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0024_downloadedreports_assessable_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='assessable_income',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='balance_tax_payable',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='document_metadata',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='tax_year',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='taxable_income',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='tin_number',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='total_tax_payable',
        ),
    ]
