# Generated by Django 4.2.20 on 2025-06-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0025_remove_downloadedreports_assessable_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='file_format',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='downloadedreports',
            name='user',
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
