# Generated by Django 4.2.20 on 2025-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0026_remove_downloadedreports_file_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='username',
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
