# Generated by Django 4.2.20 on 2025-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0027_remove_downloadedreports_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedreports',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
