# Generated by Django 4.2.20 on 2025-06-13 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_report', '0028_downloadedreports_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='user_id',
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
