# Generated by Django 4.2.20 on 2025-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0029_remove_downloadedreports_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='user',
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
