# Generated by Django 4.2.20 on 2025-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_report', '0030_remove_downloadedreports_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadedreports',
            name='full_name',
        ),
        migrations.AddField(
            model_name='downloadedreports',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
