# Generated by Django 4.2.20 on 2025-06-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taxdeadline',
            table='tax_due_dates',
        ),
    ]
