# Generated by Django 4.2.20 on 2025-06-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_notifications', '0002_alter_taxdeadline_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='NotificationHistory',
        ),
        migrations.DeleteModel(
            name='TaxDeadline',
        ),
        migrations.DeleteModel(
            name='UserNotificationPreference',
        ),
    ]
