# Generated by Django 4.2.20 on 2025-05-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_taxhistory'),
    ]

    operations = [
    ]
