# Generated by Django 4.2.20 on 2025-05-14 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_alter_taxhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxhistory',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='TaxHistory',
        ),
    ]
