# Generated by Django 4.2.20 on 2025-05-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_taxconversation_taxmessage_delete_chatmessage_and_more'),
    ]

    operations = [
    ]
