# Generated by Django 4.2.20 on 2025-06-18 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0008_auto_20250514_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
